"""tabelas do core

Revision ID: 6acb578bd5e6
Revises: 
Create Date: 2026-05-28 13:57:04.690054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6acb578bd5e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizacoes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('dono_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dono_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('times',
    sa.Column('organizacao_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agentes',
    sa.Column('time_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('agent_md', sa.Text(), nullable=True),
    sa.Column('skill_md', sa.Text(), nullable=True),
    sa.Column('tools_md', sa.Text(), nullable=True),
    sa.Column('soul_md', sa.Text(), nullable=True),
    sa.Column('modelo_ia', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_um_lider_por_time', 'agentes', ['time_id'], unique=True, postgresql_where=sa.text("papel = 'lider'"))
    op.create_table('automacoes',
    sa.Column('time_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_gatilho', sa.String(length=50), nullable=False),
    sa.Column('configuracao_gatilho', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cadeia', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrumentos',
    sa.Column('time_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('configuracao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agente_instrumentos',
    sa.Column('agente_id', sa.UUID(), nullable=False),
    sa.Column('instrumento_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agente_id', 'instrumento_id')
    )
    op.create_table('execucoes',
    sa.Column('automacao_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'aguardando'"), nullable=False),
    sa.Column('entrada', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automacao_id'], ['automacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passos_execucao',
    sa.Column('execucao_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('agente_id', sa.UUID(), nullable=True),
    sa.Column('entrada', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saida', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=30), server_default=sa.text("'aguardando'"), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passos_execucao')
    op.drop_table('execucoes')
    op.drop_table('agente_instrumentos')
    op.drop_table('instrumentos')
    op.drop_table('automacoes')
    op.drop_index('uq_um_lider_por_time', table_name='agentes', postgresql_where=sa.text("papel = 'lider'"))
    op.drop_table('agentes')
    op.drop_table('times')
    op.drop_table('organizacoes')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
