"""fase 7 - cofre de chaves

Revision ID: 73ecf4dbc909
Revises: cf6de832ad21
Create Date: 2026-06-04 19:55:56.730956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ecf4dbc909'
down_revision: Union[str, Sequence[str], None] = 'cf6de832ad21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chaves_api',
    sa.Column('organizacao_id', sa.UUID(), nullable=True),
    sa.Column('tipo_ia', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=40), nullable=False),
    sa.Column('valor_cifrado', sa.Text(), nullable=False),
    sa.Column('ultimos4', sa.String(length=8), nullable=True),
    sa.Column('apelido', sa.String(length=200), nullable=True),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_chave_org_tipo_provedor', 'chaves_api', ['organizacao_id', 'tipo_ia', 'provedor'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_chave_org_tipo_provedor', table_name='chaves_api', postgresql_nulls_not_distinct=True)
    op.drop_table('chaves_api')
    # ### end Alembic commands ###
