"""fase 7-B - cofre de segredos de instrumentos

Revision ID: b26cc22ca49a
Revises: 73ecf4dbc909
Create Date: 2026-06-06 13:32:26.094776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26cc22ca49a'
down_revision: Union[str, Sequence[str], None] = '73ecf4dbc909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segredos_instrumento',
    sa.Column('instrumento_id', sa.UUID(), nullable=False),
    sa.Column('campo', sa.String(length=80), nullable=False),
    sa.Column('valor_cifrado', sa.Text(), nullable=False),
    sa.Column('ultimos4', sa.String(length=8), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_segredo_instrumento_campo', 'segredos_instrumento', ['instrumento_id', 'campo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_segredo_instrumento_campo', table_name='segredos_instrumento')
    op.drop_table('segredos_instrumento')
    # ### end Alembic commands ###
