"""fase 6 - identidade e papeis

Revision ID: cf6de832ad21
Revises: 0b2869af154a
Create Date: 2026-06-04 13:48:13.967438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6de832ad21'
down_revision: Union[str, Sequence[str], None] = '0b2869af154a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('recurso_tipo', sa.String(length=40), nullable=True),
    sa.Column('recurso_id', sa.UUID(), nullable=True),
    sa.Column('organizacao_id', sa.UUID(), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convites',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('organizacao_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pendente'"), nullable=False),
    sa.Column('convidado_por_id', sa.UUID(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convidado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_convite_email_org', 'convites', ['email', 'organizacao_id'], unique=False)
    op.create_table('membros',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('organizacao_id', sa.UUID(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_membro_usuario_org', 'membros', ['usuario_id', 'organizacao_id'], unique=True)
    op.add_column('usuarios', sa.Column('auth_id', sa.UUID(), nullable=True))
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_unique_constraint('uq_usuarios_auth_id', 'usuarios', ['auth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuarios_auth_id', 'usuarios', type_='unique')
    op.drop_column('usuarios', 'ativo')
    op.drop_column('usuarios', 'auth_id')
    op.drop_index('uq_membro_usuario_org', table_name='membros')
    op.drop_table('membros')
    op.drop_index('ix_convite_email_org', table_name='convites')
    op.drop_table('convites')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
