"""fase 9 - ia criadora (conversas_criacao)

Revision ID: fcf05d5f64f7
Revises: b26cc22ca49a
Create Date: 2026-06-06 18:37:34.898821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcf05d5f64f7'
down_revision: Union[str, Sequence[str], None] = 'b26cc22ca49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversas_criacao',
    sa.Column('organizacao_id', sa.UUID(), nullable=False),
    sa.Column('criada_por_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'rascunho'"), nullable=False),
    sa.Column('mensagens', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('rascunho', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('time_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizacao_id'], ['organizacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversa_criacao_org', 'conversas_criacao', ['organizacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversa_criacao_org', table_name='conversas_criacao')
    op.drop_table('conversas_criacao')
    # ### end Alembic commands ###
