// Catálogo curado de ícones para instrumentos (Font Awesome free).
//
// Exceção pontual ao DESIGN-SYSTEM §8 (lucide-only): aqui o usuário escolhe um
// ícone para o instrumento, e a Font Awesome traz os LOGOS DE MARCA (WhatsApp,
// Telegram, Google, WordPress…) que o lucide não tem. Toda a iconografia de UI
// segue lucide; isto vale só para o ícone do instrumento.
//
// Cada ícone é importado EXPLICITAMENTE (tree-shaking: só o que está aqui entra
// no bundle — NÃO embarcamos as ~1900 figuras da FA, que pesariam centenas de KB
// no app inteiro). O catálogo é grande de propósito (cobre quase tudo); para algo
// raríssimo que falte, basta adicionar uma linha (e o import correspondente).

import { config, type IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAmazon,
  faAmazonPay,
  faAndroid,
  faAngular,
  faApple,
  faApplePay,
  faAws,
  faBehance,
  faBitbucket,
  faBluesky,
  faBootstrap,
  faCcMastercard,
  faCcVisa,
  faChrome,
  faCloudflare,
  faCodepen,
  faConfluence,
  faCss3,
  faDiscord,
  faDocker,
  faDribbble,
  faDropbox,
  faDrupal,
  faEdge,
  faFacebook,
  faFacebookMessenger,
  faFigma,
  faFirefoxBrowser,
  faGithub,
  faGitlab,
  faGoogle,
  faGoogleDrive,
  faGooglePay,
  faGooglePlay,
  faHtml5,
  faHubspot,
  faInstagram,
  faJava,
  faJira,
  faJoomla,
  faJs,
  faLine,
  faLinkedin,
  faLinux,
  faMagento,
  faMailchimp,
  faMastodon,
  faMedium,
  faMeta,
  faMicrosoft,
  faNodeJs,
  faNotion,
  faNpm,
  faPaypal,
  faPhp,
  faPinterest,
  faPlaystation,
  faPython,
  faReact,
  faReddit,
  faSafari,
  faSalesforce,
  faShopify,
  faSkype,
  faSlack,
  faSnapchat,
  faSoundcloud,
  faSpotify,
  faSquarespace,
  faStackOverflow,
  faSteam,
  faStripe,
  faTelegram,
  faThreads,
  faTiktok,
  faTrello,
  faTwitch,
  faUbuntu,
  faViber,
  faVimeo,
  faVk,
  faVuejs,
  faWeixin,
  faWhatsapp,
  faWindows,
  faWix,
  faWordpress,
  faXbox,
  faXTwitter,
  faYoutube,
  faZoom,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAddressBook,
  faArrowsRotate,
  faAt,
  faAtom,
  faAward,
  faBagShopping,
  faBan,
  faBasketShopping,
  faBatteryFull,
  faBell,
  faBellConcierge,
  faBolt,
  faBook,
  faBookOpen,
  faBookOpenReader,
  faBox,
  faBoxesStacked,
  faBoxOpen,
  faBrain,
  faBriefcase,
  faBrush,
  faBug,
  faBuilding,
  faBuildingColumns,
  faBuildingUser,
  faBullhorn,
  faBullseye,
  faBusinessTime,
  faCalculator,
  faCalendarCheck,
  faCalendarDays,
  faCalendarPlus,
  faCamera,
  faCameraRetro,
  faCartPlus,
  faCartShopping,
  faChalkboardUser,
  faChartArea,
  faChartBar,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChartSimple,
  faCheck,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCirclePlay,
  faCircleQuestion,
  faCircleXmark,
  faClapperboard,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faClockRotateLeft,
  faCloud,
  faCloudArrowDown,
  faCloudArrowUp,
  faCloudSun,
  faCode,
  faCodeBranch,
  faCodeCommit,
  faCodeMerge,
  faCodePullRequest,
  faCoins,
  faComment,
  faCommentDots,
  faComments,
  faCommentSms,
  faCompass,
  faCopy,
  faCreditCard,
  faCropSimple,
  faCrown,
  faCube,
  faCubes,
  faDatabase,
  faDiagramProject,
  faDice,
  faDna,
  faDolly,
  faDownload,
  faDroplet,
  faEarthAmericas,
  faEnvelope,
  faEnvelopeOpenText,
  faEnvelopesBulk,
  faEye,
  faEyeSlash,
  faFeather,
  faFileCode,
  faFileCsv,
  faFileExcel,
  faFileExport,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileLines,
  faFilePdf,
  faFilePowerpoint,
  faFileWord,
  faFileZipper,
  faFilm,
  faFilter,
  faFingerprint,
  faFire,
  faFlag,
  faFlagCheckered,
  faFlask,
  faFloppyDisk,
  faFolder,
  faFolderOpen,
  faFolderTree,
  faForward,
  faGamepad,
  faGauge,
  faGaugeHigh,
  faGavel,
  faGear,
  faGears,
  faGift,
  faGlobe,
  faGraduationCap,
  faHammer,
  faHandHoldingDollar,
  faHandHoldingHeart,
  faHands,
  faHandshake,
  faHandshakeAngle,
  faHardDrive,
  faHashtag,
  faHeadphones,
  faHeadset,
  faHeart,
  faHeartPulse,
  faHospital,
  faHourglassHalf,
  faHouse,
  faIdBadge,
  faIdCard,
  faImage,
  faImages,
  faInbox,
  faIndustry,
  faKey,
  faKeyboard,
  faLandmark,
  faLanguage,
  faLayerGroup,
  faLeaf,
  faLightbulb,
  faLink,
  faList,
  faListCheck,
  faListOl,
  faListUl,
  faLocationArrow,
  faLocationDot,
  faLock,
  faLockOpen,
  faMagnet,
  faMagnifyingGlass,
  faMagnifyingGlassPlus,
  faMap,
  faMapLocationDot,
  faMapPin,
  faMedal,
  faMemory,
  faMessage,
  faMicrochip,
  faMicrophone,
  faMicrophoneLines,
  faMinus,
  faMobileScreen,
  faMobileScreenButton,
  faMoneyBill,
  faMoneyBillTransfer,
  faMoneyCheckDollar,
  faMoon,
  faMugHot,
  faMusic,
  faNetworkWired,
  faNewspaper,
  faNotesMedical,
  faObjectGroup,
  faPaintbrush,
  faPalette,
  faPaperPlane,
  faPause,
  faPen,
  faPencil,
  faPenNib,
  faPenRuler,
  faPenToSquare,
  faPeopleGroup,
  faPercent,
  faPhone,
  faPhoneVolume,
  faPhotoFilm,
  faPiggyBank,
  faPills,
  faPlaneDeparture,
  faPlay,
  faPlug,
  faPlus,
  faPodcast,
  faPowerOff,
  faPuzzlePiece,
  faQuoteLeft,
  faReceipt,
  faRecycle,
  faRepeat,
  faRobot,
  faRotate,
  faRoute,
  faRss,
  faRulerCombined,
  faSackDollar,
  faScaleBalanced,
  faSchool,
  faScrewdriverWrench,
  faSeedling,
  faServer,
  faShapes,
  faShare,
  faShareNodes,
  faShield,
  faShieldHalved,
  faShip,
  faShop,
  faSitemap,
  faSliders,
  faSpellCheck,
  faStar,
  faStethoscope,
  faStop,
  faStopwatch,
  faStore,
  faSun,
  faSwatchbook,
  faSyringe,
  faTable,
  faTableCells,
  faTableList,
  faTag,
  faTags,
  faTemperatureHalf,
  faTerminal,
  faThumbsDown,
  faThumbsUp,
  faTicket,
  faToolbox,
  faTowerBroadcast,
  faTrainSubway,
  faTrash,
  faTrashCan,
  faTree,
  faTriangleExclamation,
  faTrophy,
  faTruck,
  faTruckFast,
  faUnlock,
  faUpload,
  faUserDoctor,
  faUserGear,
  faUserGroup,
  faUserLock,
  faUserPlus,
  faUsers,
  faUserShield,
  faUserTie,
  faUtensils,
  faVial,
  faVideo,
  faVoicemail,
  faWallet,
  faWandMagicSparkles,
  faWarehouse,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

// O componente React injeta o <svg> inline; desligamos a inserção automática de
// CSS global da FA (evita flicker/conflito no Next App Router).
config.autoAddCss = false;

export type IconeCatalogo = {
  id: string; // ex.: "fab:whatsapp", "fas:database"
  nome: string;
  icon: IconDefinition;
  termos: string; // palavras de busca (pt-br + en), minúsculas
};

// Marcas (logos) — o motivo de usar Font Awesome aqui.
const MARCAS: IconeCatalogo[] = [
  { id: "fab:whatsapp", nome: "WhatsApp", icon: faWhatsapp, termos: "whatsapp zap mensagem chat" },
  { id: "fab:telegram", nome: "Telegram", icon: faTelegram, termos: "telegram bot mensagem chat" },
  { id: "fab:google", nome: "Google", icon: faGoogle, termos: "google busca pesquisa" },
  { id: "fab:google-drive", nome: "Google Drive", icon: faGoogleDrive, termos: "google drive arquivo nuvem" },
  { id: "fab:wordpress", nome: "WordPress", icon: faWordpress, termos: "wordpress blog site publicar cms" },
  { id: "fab:slack", nome: "Slack", icon: faSlack, termos: "slack mensagem time" },
  { id: "fab:discord", nome: "Discord", icon: faDiscord, termos: "discord mensagem comunidade" },
  { id: "fab:instagram", nome: "Instagram", icon: faInstagram, termos: "instagram insta rede social foto" },
  { id: "fab:facebook", nome: "Facebook", icon: faFacebook, termos: "facebook rede social meta" },
  { id: "fab:messenger", nome: "Messenger", icon: faFacebookMessenger, termos: "messenger facebook mensagem chat" },
  { id: "fab:meta", nome: "Meta", icon: faMeta, termos: "meta facebook" },
  { id: "fab:linkedin", nome: "LinkedIn", icon: faLinkedin, termos: "linkedin rede profissional" },
  { id: "fab:youtube", nome: "YouTube", icon: faYoutube, termos: "youtube video" },
  { id: "fab:tiktok", nome: "TikTok", icon: faTiktok, termos: "tiktok video rede social" },
  { id: "fab:x-twitter", nome: "X (Twitter)", icon: faXTwitter, termos: "x twitter tuite rede social" },
  { id: "fab:threads", nome: "Threads", icon: faThreads, termos: "threads meta rede social" },
  { id: "fab:mastodon", nome: "Mastodon", icon: faMastodon, termos: "mastodon rede social" },
  { id: "fab:bluesky", nome: "Bluesky", icon: faBluesky, termos: "bluesky rede social" },
  { id: "fab:pinterest", nome: "Pinterest", icon: faPinterest, termos: "pinterest imagem" },
  { id: "fab:reddit", nome: "Reddit", icon: faReddit, termos: "reddit forum" },
  { id: "fab:snapchat", nome: "Snapchat", icon: faSnapchat, termos: "snapchat rede social foto" },
  { id: "fab:vk", nome: "VK", icon: faVk, termos: "vk rede social" },
  { id: "fab:spotify", nome: "Spotify", icon: faSpotify, termos: "spotify audio musica" },
  { id: "fab:soundcloud", nome: "SoundCloud", icon: faSoundcloud, termos: "soundcloud audio musica" },
  { id: "fab:vimeo", nome: "Vimeo", icon: faVimeo, termos: "vimeo video" },
  { id: "fab:twitch", nome: "Twitch", icon: faTwitch, termos: "twitch stream video live" },
  { id: "fab:github", nome: "GitHub", icon: faGithub, termos: "github git codigo repositorio" },
  { id: "fab:gitlab", nome: "GitLab", icon: faGitlab, termos: "gitlab git codigo repositorio" },
  { id: "fab:bitbucket", nome: "Bitbucket", icon: faBitbucket, termos: "bitbucket git codigo repositorio" },
  { id: "fab:jira", nome: "Jira", icon: faJira, termos: "jira atlassian tarefa projeto" },
  { id: "fab:confluence", nome: "Confluence", icon: faConfluence, termos: "confluence atlassian wiki docs" },
  { id: "fab:notion", nome: "Notion", icon: faNotion, termos: "notion notas docs wiki" },
  { id: "fab:figma", nome: "Figma", icon: faFigma, termos: "figma design ui" },
  { id: "fab:codepen", nome: "CodePen", icon: faCodepen, termos: "codepen codigo frontend" },
  { id: "fab:stack-overflow", nome: "Stack Overflow", icon: faStackOverflow, termos: "stack overflow codigo duvida" },
  { id: "fab:medium", nome: "Medium", icon: faMedium, termos: "medium blog artigo" },
  { id: "fab:stripe", nome: "Stripe", icon: faStripe, termos: "stripe pagamento cobranca" },
  { id: "fab:paypal", nome: "PayPal", icon: faPaypal, termos: "paypal pagamento" },
  { id: "fab:google-pay", nome: "Google Pay", icon: faGooglePay, termos: "google pay pagamento" },
  { id: "fab:apple-pay", nome: "Apple Pay", icon: faApplePay, termos: "apple pay pagamento" },
  { id: "fab:amazon-pay", nome: "Amazon Pay", icon: faAmazonPay, termos: "amazon pay pagamento" },
  { id: "fab:cc-visa", nome: "Visa", icon: faCcVisa, termos: "visa cartao pagamento" },
  { id: "fab:cc-mastercard", nome: "Mastercard", icon: faCcMastercard, termos: "mastercard cartao pagamento" },
  { id: "fab:shopify", nome: "Shopify", icon: faShopify, termos: "shopify loja ecommerce" },
  { id: "fab:magento", nome: "Magento", icon: faMagento, termos: "magento loja ecommerce" },
  { id: "fab:wix", nome: "Wix", icon: faWix, termos: "wix site construtor" },
  { id: "fab:squarespace", nome: "Squarespace", icon: faSquarespace, termos: "squarespace site" },
  { id: "fab:drupal", nome: "Drupal", icon: faDrupal, termos: "drupal cms site" },
  { id: "fab:joomla", nome: "Joomla", icon: faJoomla, termos: "joomla cms site" },
  { id: "fab:mailchimp", nome: "Mailchimp", icon: faMailchimp, termos: "mailchimp email marketing" },
  { id: "fab:hubspot", nome: "HubSpot", icon: faHubspot, termos: "hubspot crm marketing" },
  { id: "fab:salesforce", nome: "Salesforce", icon: faSalesforce, termos: "salesforce crm vendas" },
  { id: "fab:zoom", nome: "Zoom", icon: faZoom, termos: "zoom video reuniao" },
  { id: "fab:dropbox", nome: "Dropbox", icon: faDropbox, termos: "dropbox arquivo nuvem" },
  { id: "fab:microsoft", nome: "Microsoft", icon: faMicrosoft, termos: "microsoft office" },
  { id: "fab:apple", nome: "Apple", icon: faApple, termos: "apple ios mac" },
  { id: "fab:amazon", nome: "Amazon", icon: faAmazon, termos: "amazon aws loja" },
  { id: "fab:aws", nome: "AWS", icon: faAws, termos: "aws amazon nuvem cloud servidor" },
  { id: "fab:cloudflare", nome: "Cloudflare", icon: faCloudflare, termos: "cloudflare cdn dns" },
  { id: "fab:docker", nome: "Docker", icon: faDocker, termos: "docker container devops" },
  { id: "fab:trello", nome: "Trello", icon: faTrello, termos: "trello quadro tarefa" },
  { id: "fab:windows", nome: "Windows", icon: faWindows, termos: "windows microsoft so" },
  { id: "fab:linux", nome: "Linux", icon: faLinux, termos: "linux so servidor" },
  { id: "fab:ubuntu", nome: "Ubuntu", icon: faUbuntu, termos: "ubuntu linux so" },
  { id: "fab:android", nome: "Android", icon: faAndroid, termos: "android celular app" },
  { id: "fab:google-play", nome: "Google Play", icon: faGooglePlay, termos: "google play loja app" },
  { id: "fab:chrome", nome: "Chrome", icon: faChrome, termos: "chrome navegador browser" },
  { id: "fab:firefox", nome: "Firefox", icon: faFirefoxBrowser, termos: "firefox navegador browser" },
  { id: "fab:edge", nome: "Edge", icon: faEdge, termos: "edge navegador browser microsoft" },
  { id: "fab:safari", nome: "Safari", icon: faSafari, termos: "safari navegador browser apple" },
  { id: "fab:steam", nome: "Steam", icon: faSteam, termos: "steam jogo game" },
  { id: "fab:playstation", nome: "PlayStation", icon: faPlaystation, termos: "playstation jogo game" },
  { id: "fab:xbox", nome: "Xbox", icon: faXbox, termos: "xbox jogo game microsoft" },
  { id: "fab:weixin", nome: "WeChat", icon: faWeixin, termos: "wechat weixin mensagem chat china" },
  { id: "fab:line", nome: "LINE", icon: faLine, termos: "line mensagem chat" },
  { id: "fab:viber", nome: "Viber", icon: faViber, termos: "viber mensagem chat" },
  { id: "fab:skype", nome: "Skype", icon: faSkype, termos: "skype chamada video" },
  { id: "fab:behance", nome: "Behance", icon: faBehance, termos: "behance design portfolio" },
  { id: "fab:dribbble", nome: "Dribbble", icon: faDribbble, termos: "dribbble design portfolio" },
  { id: "fab:react", nome: "React", icon: faReact, termos: "react codigo frontend" },
  { id: "fab:vuejs", nome: "Vue.js", icon: faVuejs, termos: "vue vuejs codigo frontend" },
  { id: "fab:angular", nome: "Angular", icon: faAngular, termos: "angular codigo frontend" },
  { id: "fab:node-js", nome: "Node.js", icon: faNodeJs, termos: "node nodejs codigo backend" },
  { id: "fab:python", nome: "Python", icon: faPython, termos: "python codigo backend" },
  { id: "fab:js", nome: "JavaScript", icon: faJs, termos: "javascript js codigo" },
  { id: "fab:java", nome: "Java", icon: faJava, termos: "java codigo" },
  { id: "fab:php", nome: "PHP", icon: faPhp, termos: "php codigo" },
  { id: "fab:html5", nome: "HTML5", icon: faHtml5, termos: "html codigo web" },
  { id: "fab:css3", nome: "CSS3", icon: faCss3, termos: "css codigo estilo" },
  { id: "fab:bootstrap", nome: "Bootstrap", icon: faBootstrap, termos: "bootstrap css frontend" },
  { id: "fab:npm", nome: "npm", icon: faNpm, termos: "npm pacote node" },
];

// Conceitos (genéricos) — para instrumentos que não são de uma marca.
const CONCEITOS: IconeCatalogo[] = [
  // Web, busca, dados, infra
  { id: "fas:globe", nome: "Web", icon: faGlobe, termos: "web internet site globo mundo" },
  { id: "fas:earth-americas", nome: "Mundo", icon: faEarthAmericas, termos: "mundo terra globo internacional" },
  { id: "fas:language", nome: "Idioma", icon: faLanguage, termos: "idioma traducao lingua" },
  { id: "fas:magnifying-glass", nome: "Busca", icon: faMagnifyingGlass, termos: "busca pesquisa lupa procurar" },
  { id: "fas:magnifying-glass-plus", nome: "Buscar mais", icon: faMagnifyingGlassPlus, termos: "busca zoom pesquisa detalhe" },
  { id: "fas:filter", nome: "Filtro", icon: faFilter, termos: "filtro filtrar refinar" },
  { id: "fas:database", nome: "Banco de dados", icon: faDatabase, termos: "banco dados sql database" },
  { id: "fas:table", nome: "Tabela", icon: faTable, termos: "tabela planilha dados" },
  { id: "fas:table-cells", nome: "Planilha", icon: faTableCells, termos: "planilha celulas tabela excel" },
  { id: "fas:server", nome: "Servidor", icon: faServer, termos: "servidor server api host" },
  { id: "fas:network-wired", nome: "Rede", icon: faNetworkWired, termos: "rede network conexao infra" },
  { id: "fas:hard-drive", nome: "Disco", icon: faHardDrive, termos: "disco hd armazenamento storage" },
  { id: "fas:memory", nome: "Memória", icon: faMemory, termos: "memoria ram" },
  { id: "fas:microchip", nome: "Chip / Processador", icon: faMicrochip, termos: "chip processador hardware" },
  { id: "fas:sitemap", nome: "Estrutura", icon: faSitemap, termos: "estrutura mapa hierarquia organograma" },
  { id: "fas:diagram-project", nome: "Diagrama", icon: faDiagramProject, termos: "diagrama fluxo projeto" },
  { id: "fas:plug", nome: "Conexão", icon: faPlug, termos: "conexao plug integracao api mcp" },
  { id: "fas:cloud", nome: "Nuvem", icon: faCloud, termos: "nuvem cloud armazenamento" },
  { id: "fas:cloud-arrow-up", nome: "Upload nuvem", icon: faCloudArrowUp, termos: "upload enviar nuvem cloud subir" },
  { id: "fas:cloud-arrow-down", nome: "Download nuvem", icon: faCloudArrowDown, termos: "download baixar nuvem cloud" },
  // Código / dev
  { id: "fas:code", nome: "Código", icon: faCode, termos: "codigo code api rest json" },
  { id: "fas:terminal", nome: "Terminal", icon: faTerminal, termos: "terminal console shell comando" },
  { id: "fas:file-code", nome: "Arquivo de código", icon: faFileCode, termos: "codigo arquivo script" },
  { id: "fas:code-branch", nome: "Branch", icon: faCodeBranch, termos: "branch git ramo versao" },
  { id: "fas:code-commit", nome: "Commit", icon: faCodeCommit, termos: "commit git versao" },
  { id: "fas:code-merge", nome: "Merge", icon: faCodeMerge, termos: "merge git juntar" },
  { id: "fas:code-pull-request", nome: "Pull request", icon: faCodePullRequest, termos: "pull request pr git" },
  { id: "fas:bug", nome: "Bug", icon: faBug, termos: "bug erro defeito" },
  { id: "fas:terminal-gears", nome: "Engrenagens", icon: faGears, termos: "engrenagens config sistema processo" },
  // Comunicação
  { id: "fas:paper-plane", nome: "Enviar", icon: faPaperPlane, termos: "enviar mensagem envio" },
  { id: "fas:comment", nome: "Mensagem", icon: faComment, termos: "mensagem balao chat" },
  { id: "fas:comment-dots", nome: "Conversando", icon: faCommentDots, termos: "conversa digitando chat" },
  { id: "fas:comments", nome: "Conversa", icon: faComments, termos: "conversa chat mensagem atendimento" },
  { id: "fas:comment-sms", nome: "SMS", icon: faCommentSms, termos: "sms torpedo mensagem" },
  { id: "fas:message", nome: "Recado", icon: faMessage, termos: "recado mensagem chat" },
  { id: "fas:headset", nome: "Atendimento", icon: faHeadset, termos: "atendimento suporte sac" },
  { id: "fas:envelope", nome: "E-mail", icon: faEnvelope, termos: "email correio mensagem" },
  { id: "fas:envelope-open-text", nome: "E-mail aberto", icon: faEnvelopeOpenText, termos: "email aberto newsletter" },
  { id: "fas:envelopes-bulk", nome: "E-mail em massa", icon: faEnvelopesBulk, termos: "email massa disparo newsletter marketing" },
  { id: "fas:inbox", nome: "Caixa de entrada", icon: faInbox, termos: "inbox caixa entrada recebido" },
  { id: "fas:phone", nome: "Telefone", icon: faPhone, termos: "telefone ligacao voz" },
  { id: "fas:phone-volume", nome: "Chamada", icon: faPhoneVolume, termos: "chamada ligacao telefone" },
  { id: "fas:voicemail", nome: "Correio de voz", icon: faVoicemail, termos: "voz correio recado" },
  { id: "fas:mobile-screen", nome: "Celular", icon: faMobileScreen, termos: "celular telefone mobile app" },
  { id: "fas:mobile-screen-button", nome: "Smartphone", icon: faMobileScreenButton, termos: "smartphone celular mobile" },
  { id: "fas:at", nome: "Arroba", icon: faAt, termos: "arroba email usuario mencao" },
  { id: "fas:hashtag", nome: "Hashtag", icon: faHashtag, termos: "hashtag tag rede social" },
  { id: "fas:rss", nome: "RSS / Feed", icon: faRss, termos: "rss feed assinatura noticia" },
  { id: "fas:tower-broadcast", nome: "Transmissão", icon: faTowerBroadcast, termos: "transmissao broadcast sinal antena" },
  { id: "fas:share-nodes", nome: "Compartilhar", icon: faShareNodes, termos: "compartilhar share rede" },
  { id: "fas:share", nome: "Encaminhar", icon: faShare, termos: "encaminhar compartilhar enviar" },
  // Conteúdo / arquivos
  { id: "fas:robot", nome: "Robô / IA", icon: faRobot, termos: "robo ia bot agente" },
  { id: "fas:brain", nome: "IA / Inteligência", icon: faBrain, termos: "ia inteligencia cerebro brain" },
  { id: "fas:image", nome: "Imagem", icon: faImage, termos: "imagem foto figura gerar" },
  { id: "fas:images", nome: "Galeria", icon: faImages, termos: "galeria imagens fotos album" },
  { id: "fas:photo-film", nome: "Mídia", icon: faPhotoFilm, termos: "midia foto video" },
  { id: "fas:camera", nome: "Câmera", icon: faCamera, termos: "camera foto fotografia" },
  { id: "fas:camera-retro", nome: "Foto", icon: faCameraRetro, termos: "foto camera retro fotografia" },
  { id: "fas:video", nome: "Vídeo", icon: faVideo, termos: "video filme camera" },
  { id: "fas:film", nome: "Filme", icon: faFilm, termos: "filme video cinema" },
  { id: "fas:clapperboard", nome: "Produção de vídeo", icon: faClapperboard, termos: "video producao claquete cinema" },
  { id: "fas:music", nome: "Música", icon: faMusic, termos: "musica audio som" },
  { id: "fas:microphone", nome: "Áudio", icon: faMicrophone, termos: "audio microfone voz transcricao" },
  { id: "fas:microphone-lines", nome: "Gravação", icon: faMicrophoneLines, termos: "gravacao audio podcast microfone" },
  { id: "fas:headphones", nome: "Fone", icon: faHeadphones, termos: "fone audio escutar" },
  { id: "fas:podcast", nome: "Podcast", icon: faPodcast, termos: "podcast audio episodio" },
  { id: "fas:file-pdf", nome: "PDF", icon: faFilePdf, termos: "pdf documento arquivo" },
  { id: "fas:file-lines", nome: "Documento", icon: faFileLines, termos: "documento arquivo texto" },
  { id: "fas:file-csv", nome: "CSV", icon: faFileCsv, termos: "csv planilha dados arquivo" },
  { id: "fas:file-excel", nome: "Excel", icon: faFileExcel, termos: "excel planilha xls dados" },
  { id: "fas:file-word", nome: "Word", icon: faFileWord, termos: "word documento doc texto" },
  { id: "fas:file-powerpoint", nome: "PowerPoint", icon: faFilePowerpoint, termos: "powerpoint slide apresentacao ppt" },
  { id: "fas:file-zipper", nome: "Arquivo ZIP", icon: faFileZipper, termos: "zip arquivo compactado" },
  { id: "fas:file-export", nome: "Exportar", icon: faFileExport, termos: "exportar export arquivo saida" },
  { id: "fas:file-import", nome: "Importar", icon: faFileImport, termos: "importar import arquivo entrada" },
  { id: "fas:folder", nome: "Pasta", icon: faFolder, termos: "pasta arquivo diretorio" },
  { id: "fas:folder-open", nome: "Pasta aberta", icon: faFolderOpen, termos: "pasta aberta arquivo diretorio" },
  { id: "fas:folder-tree", nome: "Pastas", icon: faFolderTree, termos: "pastas arvore diretorio estrutura" },
  { id: "fas:book", nome: "Livro", icon: faBook, termos: "livro biblioteca conhecimento" },
  { id: "fas:book-open", nome: "Livro aberto", icon: faBookOpen, termos: "livro aberto leitura conhecimento" },
  { id: "fas:book-open-reader", nome: "Leitura", icon: faBookOpenReader, termos: "leitura estudo aprender" },
  { id: "fas:newspaper", nome: "Notícia / Conteúdo", icon: faNewspaper, termos: "noticia conteudo artigo jornal" },
  { id: "fas:pen-to-square", nome: "Editar / Escrever", icon: faPenToSquare, termos: "editar escrever redacao" },
  { id: "fas:pen", nome: "Caneta", icon: faPen, termos: "caneta escrever editar" },
  { id: "fas:pencil", nome: "Lápis", icon: faPencil, termos: "lapis escrever editar" },
  { id: "fas:pen-nib", nome: "Redação", icon: faPenNib, termos: "redacao escrever copywriting" },
  { id: "fas:pen-ruler", nome: "Design", icon: faPenRuler, termos: "design criar projeto" },
  { id: "fas:feather", nome: "Escrita", icon: faFeather, termos: "escrita pena texto" },
  { id: "fas:quote-left", nome: "Citação", icon: faQuoteLeft, termos: "citacao aspas frase" },
  { id: "fas:spell-check", nome: "Revisão", icon: faSpellCheck, termos: "revisao ortografia corrigir texto" },
  { id: "fas:keyboard", nome: "Teclado", icon: faKeyboard, termos: "teclado digitar texto" },
  { id: "fas:bullhorn", nome: "Marketing", icon: faBullhorn, termos: "marketing anuncio divulgacao megafone" },
  // Mídia / design / criação
  { id: "fas:palette", nome: "Paleta", icon: faPalette, termos: "paleta cor design arte" },
  { id: "fas:paintbrush", nome: "Pincel", icon: faPaintbrush, termos: "pincel pintar arte design" },
  { id: "fas:brush", nome: "Arte", icon: faBrush, termos: "arte pincel design" },
  { id: "fas:swatchbook", nome: "Cores", icon: faSwatchbook, termos: "cores paleta amostra design" },
  { id: "fas:wand-magic-sparkles", nome: "Mágica / Gerar", icon: faWandMagicSparkles, termos: "magica gerar ia varinha criar" },
  { id: "fas:crop-simple", nome: "Recortar", icon: faCropSimple, termos: "recortar crop imagem editar" },
  { id: "fas:eye", nome: "Visualizar", icon: faEye, termos: "ver visualizar olho preview" },
  { id: "fas:eye-slash", nome: "Ocultar", icon: faEyeSlash, termos: "ocultar esconder invisivel" },
  { id: "fas:shapes", nome: "Formas", icon: faShapes, termos: "formas figuras design" },
  { id: "fas:object-group", nome: "Agrupar", icon: faObjectGroup, termos: "agrupar objetos design" },
  { id: "fas:layer-group", nome: "Camadas", icon: faLayerGroup, termos: "camadas layers pilha" },
  { id: "fas:puzzle-piece", nome: "Integração", icon: faPuzzlePiece, termos: "integracao plugin encaixe peca" },
  { id: "fas:cube", nome: "Módulo", icon: faCube, termos: "modulo cubo objeto 3d" },
  { id: "fas:cubes", nome: "Módulos", icon: faCubes, termos: "modulos blocos cubos" },
  // Pessoas / empresa
  { id: "fas:house", nome: "Início / Casa", icon: faHouse, termos: "inicio casa home" },
  { id: "fas:building", nome: "Empresa", icon: faBuilding, termos: "empresa predio organizacao" },
  { id: "fas:building-user", nome: "Cliente empresa", icon: faBuildingUser, termos: "empresa cliente conta b2b" },
  { id: "fas:building-columns", nome: "Banco / Instituição", icon: faBuildingColumns, termos: "banco instituicao governo" },
  { id: "fas:industry", nome: "Indústria", icon: faIndustry, termos: "industria fabrica producao" },
  { id: "fas:store", nome: "Loja", icon: faStore, termos: "loja comercio varejo" },
  { id: "fas:shop", nome: "Comércio", icon: faShop, termos: "comercio loja venda" },
  { id: "fas:warehouse", nome: "Estoque", icon: faWarehouse, termos: "estoque armazem deposito" },
  { id: "fas:briefcase", nome: "Negócios", icon: faBriefcase, termos: "negocios trabalho maleta" },
  { id: "fas:user-tie", nome: "Profissional", icon: faUserTie, termos: "profissional executivo pessoa" },
  { id: "fas:users", nome: "Pessoas", icon: faUsers, termos: "pessoas usuarios equipe" },
  { id: "fas:user-group", nome: "Grupo", icon: faUserGroup, termos: "grupo equipe pessoas" },
  { id: "fas:people-group", nome: "Comunidade", icon: faPeopleGroup, termos: "comunidade pessoas publico" },
  { id: "fas:user-plus", nome: "Novo usuário", icon: faUserPlus, termos: "usuario novo cadastro lead" },
  { id: "fas:user-gear", nome: "Config usuário", icon: faUserGear, termos: "usuario config conta perfil" },
  { id: "fas:user-doctor", nome: "Médico", icon: faUserDoctor, termos: "medico saude doutor" },
  { id: "fas:address-book", nome: "Contatos", icon: faAddressBook, termos: "contatos agenda telefone" },
  { id: "fas:id-card", nome: "Cadastro", icon: faIdCard, termos: "cadastro identidade documento" },
  { id: "fas:id-badge", nome: "Crachá", icon: faIdBadge, termos: "cracha identificacao perfil" },
  { id: "fas:handshake", nome: "Acordo", icon: faHandshake, termos: "acordo parceria negocio" },
  { id: "fas:handshake-angle", nome: "Suporte", icon: faHandshakeAngle, termos: "ajuda suporte apoio" },
  { id: "fas:hands", nome: "Colaboração", icon: faHands, termos: "colaboracao maos ajuda" },
  { id: "fas:hand-holding-heart", nome: "Cuidado", icon: faHandHoldingHeart, termos: "cuidado doacao apoio" },
  { id: "fas:chalkboard-user", nome: "Treinamento", icon: faChalkboardUser, termos: "treinamento aula professor curso" },
  { id: "fas:graduation-cap", nome: "Educação", icon: faGraduationCap, termos: "educacao formatura curso ensino" },
  { id: "fas:school", nome: "Escola", icon: faSchool, termos: "escola ensino educacao" },
  // Status / ações
  { id: "fas:check", nome: "OK", icon: faCheck, termos: "ok certo confirmar check" },
  { id: "fas:circle-check", nome: "Aprovado", icon: faCircleCheck, termos: "aprovado ok sucesso confirmado" },
  { id: "fas:xmark", nome: "Fechar / X", icon: faXmark, termos: "fechar x cancelar erro" },
  { id: "fas:circle-xmark", nome: "Reprovado", icon: faCircleXmark, termos: "reprovado erro recusado cancelado" },
  { id: "fas:ban", nome: "Bloquear", icon: faBan, termos: "bloquear proibido cancelar" },
  { id: "fas:circle-exclamation", nome: "Alerta", icon: faCircleExclamation, termos: "alerta atencao aviso erro" },
  { id: "fas:triangle-exclamation", nome: "Aviso", icon: faTriangleExclamation, termos: "aviso atencao alerta perigo" },
  { id: "fas:circle-info", nome: "Informação", icon: faCircleInfo, termos: "info informacao ajuda" },
  { id: "fas:circle-question", nome: "Dúvida", icon: faCircleQuestion, termos: "duvida pergunta ajuda faq" },
  { id: "fas:plus", nome: "Adicionar", icon: faPlus, termos: "adicionar mais novo criar" },
  { id: "fas:minus", nome: "Remover", icon: faMinus, termos: "remover menos tirar" },
  { id: "fas:trash", nome: "Lixeira", icon: faTrash, termos: "lixeira excluir apagar deletar" },
  { id: "fas:trash-can", nome: "Excluir", icon: faTrashCan, termos: "excluir apagar lixeira deletar" },
  { id: "fas:copy", nome: "Copiar", icon: faCopy, termos: "copiar duplicar" },
  { id: "fas:floppy-disk", nome: "Salvar", icon: faFloppyDisk, termos: "salvar gravar disquete" },
  { id: "fas:upload", nome: "Upload", icon: faUpload, termos: "upload enviar subir arquivo" },
  { id: "fas:download", nome: "Download", icon: faDownload, termos: "download baixar arquivo" },
  { id: "fas:arrows-rotate", nome: "Sincronizar", icon: faArrowsRotate, termos: "sincronizar atualizar refresh sync" },
  { id: "fas:rotate", nome: "Atualizar", icon: faRotate, termos: "atualizar girar refresh" },
  { id: "fas:repeat", nome: "Repetir", icon: faRepeat, termos: "repetir loop reexecutar" },
  { id: "fas:play", nome: "Iniciar", icon: faPlay, termos: "iniciar play rodar executar" },
  { id: "fas:circle-play", nome: "Executar", icon: faCirclePlay, termos: "executar play rodar iniciar" },
  { id: "fas:pause", nome: "Pausar", icon: faPause, termos: "pausar parar" },
  { id: "fas:stop", nome: "Parar", icon: faStop, termos: "parar stop encerrar" },
  { id: "fas:forward", nome: "Avançar", icon: faForward, termos: "avancar pular proximo" },
  { id: "fas:power-off", nome: "Ligar/Desligar", icon: faPowerOff, termos: "ligar desligar power energia" },
  // Listas / tarefas
  { id: "fas:list", nome: "Lista", icon: faList, termos: "lista itens" },
  { id: "fas:list-check", nome: "Checklist", icon: faListCheck, termos: "checklist tarefas lista feito" },
  { id: "fas:list-ul", nome: "Lista (bullets)", icon: faListUl, termos: "lista marcadores bullets" },
  { id: "fas:list-ol", nome: "Lista numerada", icon: faListOl, termos: "lista numerada ordem passos" },
  { id: "fas:table-list", nome: "Lista em tabela", icon: faTableList, termos: "lista tabela registros" },
  { id: "fas:clipboard", nome: "Prancheta", icon: faClipboard, termos: "prancheta copiar nota" },
  { id: "fas:clipboard-list", nome: "Tarefas", icon: faClipboardList, termos: "tarefas lista prancheta" },
  { id: "fas:clipboard-check", nome: "Tarefa concluída", icon: faClipboardCheck, termos: "tarefa concluida feito check" },
  // Métricas / relatórios
  { id: "fas:chart-line", nome: "Relatório", icon: faChartLine, termos: "relatorio grafico metrica analise" },
  { id: "fas:chart-bar", nome: "Gráfico de barras", icon: faChartBar, termos: "grafico barras metrica" },
  { id: "fas:chart-column", nome: "Gráfico de colunas", icon: faChartColumn, termos: "grafico colunas metrica" },
  { id: "fas:chart-pie", nome: "Gráfico de pizza", icon: faChartPie, termos: "grafico pizza proporcao" },
  { id: "fas:chart-area", nome: "Gráfico de área", icon: faChartArea, termos: "grafico area tendencia" },
  { id: "fas:chart-simple", nome: "Indicadores", icon: faChartSimple, termos: "indicadores grafico metrica kpi" },
  { id: "fas:gauge", nome: "Painel", icon: faGauge, termos: "painel dashboard medidor" },
  { id: "fas:gauge-high", nome: "Desempenho", icon: faGaugeHigh, termos: "desempenho velocidade medidor" },
  { id: "fas:bullseye", nome: "Meta / Alvo", icon: faBullseye, termos: "meta alvo objetivo foco" },
  { id: "fas:flag", nome: "Marcador", icon: faFlag, termos: "marcador bandeira flag" },
  { id: "fas:flag-checkered", nome: "Conclusão", icon: faFlagCheckered, termos: "conclusao meta fim chegada" },
  { id: "fas:tag", nome: "Etiqueta", icon: faTag, termos: "etiqueta tag rotulo" },
  { id: "fas:tags", nome: "Etiquetas", icon: faTags, termos: "etiquetas tags categorias" },
  { id: "fas:ticket", nome: "Ticket", icon: faTicket, termos: "ticket chamado suporte ingresso" },
  // Dinheiro / comércio
  { id: "fas:cart-shopping", nome: "Carrinho", icon: faCartShopping, termos: "carrinho compra loja ecommerce" },
  { id: "fas:cart-plus", nome: "Adicionar ao carrinho", icon: faCartPlus, termos: "carrinho adicionar compra" },
  { id: "fas:bag-shopping", nome: "Sacola", icon: faBagShopping, termos: "sacola compra loja" },
  { id: "fas:basket-shopping", nome: "Cesta", icon: faBasketShopping, termos: "cesta compra mercado" },
  { id: "fas:box", nome: "Produto", icon: faBox, termos: "produto caixa item" },
  { id: "fas:box-open", nome: "Caixa aberta", icon: faBoxOpen, termos: "caixa aberta produto entrega" },
  { id: "fas:boxes-stacked", nome: "Estoque (caixas)", icon: faBoxesStacked, termos: "estoque caixas produtos" },
  { id: "fas:receipt", nome: "Recibo", icon: faReceipt, termos: "recibo nota comprovante" },
  { id: "fas:file-invoice", nome: "Nota / Fatura", icon: faFileInvoice, termos: "nota fatura fiscal documento" },
  { id: "fas:file-invoice-dollar", nome: "Cobrança", icon: faFileInvoiceDollar, termos: "cobranca fatura boleto dinheiro" },
  { id: "fas:credit-card", nome: "Pagamento", icon: faCreditCard, termos: "pagamento cartao cobranca" },
  { id: "fas:money-bill", nome: "Dinheiro", icon: faMoneyBill, termos: "dinheiro nota cash" },
  { id: "fas:money-bill-transfer", nome: "Transferência", icon: faMoneyBillTransfer, termos: "transferencia financeiro pagamento pix" },
  { id: "fas:money-check-dollar", nome: "Financeiro", icon: faMoneyCheckDollar, termos: "financeiro pagamento cheque dinheiro" },
  { id: "fas:sack-dollar", nome: "Receita", icon: faSackDollar, termos: "receita dinheiro lucro saco" },
  { id: "fas:coins", nome: "Moedas", icon: faCoins, termos: "moedas dinheiro valor" },
  { id: "fas:wallet", nome: "Carteira", icon: faWallet, termos: "carteira dinheiro saldo" },
  { id: "fas:piggy-bank", nome: "Poupança", icon: faPiggyBank, termos: "poupanca cofrinho economia" },
  { id: "fas:hand-holding-dollar", nome: "Pagar / Receber", icon: faHandHoldingDollar, termos: "pagar receber dinheiro" },
  { id: "fas:percent", nome: "Desconto", icon: faPercent, termos: "desconto porcentagem juros" },
  { id: "fas:calculator", nome: "Cálculo", icon: faCalculator, termos: "calculo calculadora conta" },
  { id: "fas:scale-balanced", nome: "Equilíbrio / Jurídico", icon: faScaleBalanced, termos: "balanca juridico equilibrio justica" },
  { id: "fas:gavel", nome: "Jurídico", icon: faGavel, termos: "juridico martelo lei decisao" },
  { id: "fas:landmark", nome: "Banco / Órgão", icon: faLandmark, termos: "banco governo instituicao" },
  // Logística / mapa / tempo
  { id: "fas:truck", nome: "Entrega", icon: faTruck, termos: "entrega caminhao frete" },
  { id: "fas:truck-fast", nome: "Entrega rápida", icon: faTruckFast, termos: "entrega rapida frete expressa" },
  { id: "fas:dolly", nome: "Logística", icon: faDolly, termos: "logistica carga carrinho" },
  { id: "fas:plane-departure", nome: "Viagem", icon: faPlaneDeparture, termos: "viagem aviao voo" },
  { id: "fas:ship", nome: "Navio", icon: faShip, termos: "navio importacao frete maritimo" },
  { id: "fas:train-subway", nome: "Transporte", icon: faTrainSubway, termos: "transporte metro trem" },
  { id: "fas:route", nome: "Rota", icon: faRoute, termos: "rota caminho percurso" },
  { id: "fas:map", nome: "Mapa", icon: faMap, termos: "mapa localizacao" },
  { id: "fas:map-location-dot", nome: "Localização (mapa)", icon: faMapLocationDot, termos: "mapa localizacao endereco gps" },
  { id: "fas:location-dot", nome: "Localização", icon: faLocationDot, termos: "localizacao mapa endereco gps" },
  { id: "fas:location-arrow", nome: "Direção", icon: faLocationArrow, termos: "direcao gps navegacao" },
  { id: "fas:map-pin", nome: "Ponto no mapa", icon: faMapPin, termos: "ponto pin local marcador" },
  { id: "fas:compass", nome: "Bússola", icon: faCompass, termos: "bussola direcao explorar" },
  { id: "fas:clock", nome: "Relógio", icon: faClock, termos: "relogio hora tempo" },
  { id: "fas:calendar", nome: "Agenda", icon: faCalendarDays, termos: "agenda calendario data evento" },
  { id: "fas:calendar-check", nome: "Compromisso", icon: faCalendarCheck, termos: "compromisso agendado data confirmado" },
  { id: "fas:calendar-plus", nome: "Agendar", icon: faCalendarPlus, termos: "agendar novo evento data" },
  { id: "fas:hourglass-half", nome: "Em andamento", icon: faHourglassHalf, termos: "andamento espera ampulheta tempo" },
  { id: "fas:stopwatch", nome: "Cronômetro", icon: faStopwatch, termos: "cronometro tempo medir" },
  { id: "fas:business-time", nome: "Expediente", icon: faBusinessTime, termos: "expediente horario trabalho prazo" },
  { id: "fas:clock-rotate-left", nome: "Histórico", icon: faClockRotateLeft, termos: "historico passado log tempo" },
  // Notificações / automação / segurança
  { id: "fas:bell", nome: "Notificação", icon: faBell, termos: "notificacao alerta sino aviso" },
  { id: "fas:bell-concierge", nome: "Chamado", icon: faBellConcierge, termos: "chamado servico atendimento sino" },
  { id: "fas:bolt", nome: "Automação", icon: faBolt, termos: "automacao raio gatilho disparo" },
  { id: "fas:link", nome: "Link / Webhook", icon: faLink, termos: "link url webhook conexao" },
  { id: "fas:gear", nome: "Configuração", icon: faGear, termos: "config engrenagem ajuste ferramenta" },
  { id: "fas:sliders", nome: "Ajustes", icon: faSliders, termos: "ajustes controles preferencias" },
  { id: "fas:screwdriver-wrench", nome: "Ferramentas", icon: faScrewdriverWrench, termos: "ferramentas manutencao reparo" },
  { id: "fas:wrench-tool", nome: "Chave (ferramenta)", icon: faHammer, termos: "ferramenta martelo construir" },
  { id: "fas:toolbox", nome: "Caixa de ferramentas", icon: faToolbox, termos: "ferramentas caixa kit" },
  { id: "fas:key", nome: "Chave / Credencial", icon: faKey, termos: "chave credencial senha api" },
  { id: "fas:lock", nome: "Cadeado", icon: faLock, termos: "cadeado seguro bloqueado privado" },
  { id: "fas:lock-open", nome: "Desbloqueado", icon: faLockOpen, termos: "desbloqueado aberto liberar" },
  { id: "fas:unlock", nome: "Liberar", icon: faUnlock, termos: "liberar desbloquear acesso" },
  { id: "fas:shield", nome: "Proteção", icon: faShield, termos: "protecao escudo seguranca" },
  { id: "fas:shield-halved", nome: "Segurança", icon: faShieldHalved, termos: "seguranca escudo protecao" },
  { id: "fas:user-shield", nome: "Privacidade", icon: faUserShield, termos: "privacidade seguranca usuario" },
  { id: "fas:user-lock", nome: "Acesso restrito", icon: faUserLock, termos: "acesso restrito permissao usuario" },
  { id: "fas:fingerprint", nome: "Identidade", icon: faFingerprint, termos: "identidade biometria digital" },
  // Saúde / ciência / natureza / diversos
  { id: "fas:stethoscope", nome: "Saúde", icon: faStethoscope, termos: "saude medico clinica" },
  { id: "fas:pills", nome: "Remédio", icon: faPills, termos: "remedio farmacia medicamento" },
  { id: "fas:syringe", nome: "Vacina", icon: faSyringe, termos: "vacina injecao saude" },
  { id: "fas:notes-medical", nome: "Prontuário", icon: faNotesMedical, termos: "prontuario ficha medica saude" },
  { id: "fas:hospital", nome: "Hospital", icon: faHospital, termos: "hospital clinica saude" },
  { id: "fas:flask", nome: "Laboratório", icon: faFlask, termos: "laboratorio quimica experimento teste" },
  { id: "fas:vial", nome: "Amostra", icon: faVial, termos: "amostra tubo laboratorio teste" },
  { id: "fas:atom", nome: "Ciência", icon: faAtom, termos: "ciencia atomo fisica" },
  { id: "fas:dna", nome: "DNA / Genética", icon: faDna, termos: "dna genetica biologia" },
  { id: "fas:magnet", nome: "Atração / Leads", icon: faMagnet, termos: "ima atracao leads captacao" },
  { id: "fas:leaf", nome: "Sustentável", icon: faLeaf, termos: "sustentavel folha verde eco" },
  { id: "fas:seedling", nome: "Crescimento", icon: faSeedling, termos: "crescimento muda planta inicio" },
  { id: "fas:tree", nome: "Árvore", icon: faTree, termos: "arvore natureza verde" },
  { id: "fas:recycle", nome: "Reciclar", icon: faRecycle, termos: "reciclar reuso eco sustentavel" },
  { id: "fas:lightbulb", nome: "Ideia", icon: faLightbulb, termos: "ideia lampada insight criativo" },
  { id: "fas:fire", nome: "Em alta", icon: faFire, termos: "alta fogo tendencia popular" },
  { id: "fas:sun", nome: "Dia / Claro", icon: faSun, termos: "dia sol claro tema" },
  { id: "fas:moon", nome: "Noite / Escuro", icon: faMoon, termos: "noite lua escuro tema" },
  { id: "fas:cloud-sun", nome: "Clima", icon: faCloudSun, termos: "clima tempo previsao sol nuvem" },
  { id: "fas:temperature-half", nome: "Temperatura", icon: faTemperatureHalf, termos: "temperatura termometro clima" },
  { id: "fas:droplet", nome: "Água / Gota", icon: faDroplet, termos: "agua gota liquido" },
  { id: "fas:battery-full", nome: "Bateria", icon: faBatteryFull, termos: "bateria energia carga" },
  { id: "fas:gamepad", nome: "Jogo", icon: faGamepad, termos: "jogo game controle" },
  { id: "fas:dice", nome: "Sorteio / Acaso", icon: faDice, termos: "sorteio dado acaso aleatorio" },
  { id: "fas:trophy", nome: "Conquista", icon: faTrophy, termos: "conquista premio trofeu vitoria" },
  { id: "fas:medal", nome: "Medalha", icon: faMedal, termos: "medalha premio conquista" },
  { id: "fas:award", nome: "Prêmio", icon: faAward, termos: "premio reconhecimento selo" },
  { id: "fas:crown", nome: "Premium", icon: faCrown, termos: "premium coroa vip destaque" },
  { id: "fas:star", nome: "Favorito", icon: faStar, termos: "favorito estrela destaque avaliacao" },
  { id: "fas:heart", nome: "Curtir", icon: faHeart, termos: "curtir coracao gostar favorito" },
  { id: "fas:heart-pulse", nome: "Vital / Monitor", icon: faHeartPulse, termos: "vital pulso monitor saude batimento" },
  { id: "fas:thumbs-up", nome: "Aprovar", icon: faThumbsUp, termos: "aprovar curtir positivo joinha" },
  { id: "fas:thumbs-down", nome: "Reprovar", icon: faThumbsDown, termos: "reprovar negativo descurtir" },
  { id: "fas:gift", nome: "Presente / Brinde", icon: faGift, termos: "presente brinde promocao" },
  { id: "fas:mug-hot", nome: "Café", icon: faMugHot, termos: "cafe bebida pausa" },
  { id: "fas:utensils", nome: "Restaurante", icon: faUtensils, termos: "restaurante comida garfo" },
  { id: "fas:ruler-combined", nome: "Medida", icon: faRulerCombined, termos: "medida regua dimensao" },
];

export const CATALOGO_ICONES: IconeCatalogo[] = [...MARCAS, ...CONCEITOS];

// Lookup O(1): id → IconDefinition (usado pelo <IconeInstrumento>).
export const MAPA_ICONES: Map<string, IconDefinition> = new Map(
  CATALOGO_ICONES.map((i) => [i.id, i.icon]),
);
